# Generated by Django 6.0.7 on 2026-07-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('course', models.CharField(choices=[('Django', 'Django'), ('MEARN-STACK', 'MEARN_STACK'), ('JAVA', 'JAVA'), ('SOFTWARE-TESTING', 'SOFTWARE_TESTING'), ('ASP.net', 'ASP.net'), ('DATASCEIENCE', 'DATASCIENCE'), ('DIGITAL-MARKETING', 'DIGITAL-MARKETING'), ('FLUTTER', 'FLUTTER')], max_length=150)),
                ('source', models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Website', 'Website'), ('WhatsApp', 'WhatsApp'), ('Walk-in', 'Walk-in'), ('Referral', 'Referral'), ('Call', 'Call')], default='Website', max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Joined', 'Joined')], default='New', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
